# Site settings
title: Caporaso Lab
description: >
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.

baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://caporasolab.us" # the base hostname & protocol for your site

author:
  fullname: Greg Caporaso
  #googleplus:
  github: biocore
  twitter: gregcaporaso
  # disqus: your_disqus_username

google_analytics: 'UA-6636235-10'

# Build settings
markdown: kramdown
